import { Scale } from 'lucide-react';
import { LegalPage } from '@/components/common/LegalPage';

const sections = [
  {
    title: 'Acceptance of Terms',
    body: [
      'By accessing or using D. Dictionary AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.',
    ],
  },
  {
    title: 'Use of the Service',
    body: [
      'D. Dictionary AI provides AI-powered dictionary, translation, and vocabulary learning tools. You agree to use the service only for lawful purposes and in accordance with these terms.',
      'You may not attempt to interfere with the service, reverse engineer it, or use it to build a competing product.',
    ],
  },
  {
    title: 'User Accounts',
    body: [
      'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account.',
      'You must be at least 13 years old to create an account.',
    ],
  },
  {
    title: 'AI-Generated Content',
    body: [
      'Definitions, translations, and responses generated by our AI are provided for informational and educational purposes and may not always be perfectly accurate. Please use them with judgment and verify important information.',
      'We are not liable for any reliance you place on AI-generated content.',
    ],
  },
  {
    title: 'Intellectual Property',
    body: [
      'The D. Dictionary AI name, logo, design, and original content are our property. We do not claim ownership of the words, definitions, or translations generated through the service.',
    ],
  },
  {
    title: 'Acceptable Use',
    body: [
      'You agree not to use the service to generate or distribute illegal, harmful, or infringing content, or to attempt to access data you are not authorized to access.',
    ],
  },
  {
    title: 'Disclaimer of Warranties',
    body: [
      'The service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee that the service will be uninterrupted, error-free, or entirely accurate.',
    ],
  },
  {
    title: 'Limitation of Liability',
    body: [
      'To the maximum extent permitted by law, D. Dictionary AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the service.',
    ],
  },
  {
    title: 'Changes to These Terms',
    body: [
      'We may update these terms from time to time. When we do, we will revise the "Last updated" date. Continued use of the service after changes are posted constitutes acceptance of the revised terms.',
    ],
  },
  {
    title: 'Contact Us',
    body: [
      'If you have any questions about these Terms of Service, please contact us at support@dictionary.ai.',
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle="The rules and guidelines for using D. Dictionary AI."
      icon={Scale}
      updated="August 4, 2026"
      current="terms"
      sections={sections}
    />
  );
}
